### ISSUE TITLE
Problem with parsing email link

### ISSUE THREAD

**Issue by gozzilli** [millermedeiros/gh-markdown-cli#10] opened 2013-04-29 08:57 UTC
Hi,

There seems to be an issue with compiling an email link such as:

``` markdown
[email us](test@example.org)
```

which returns

``` html
<p><a href="<a href='mailto:test@example.org'>test@example.org</a>">email us</a></p>
```

instead of the desired:

``` html
[email us](test@example.org)
<p><a href="test@example.org">email us</a></p>
```

Adding `mailto:` in front of the address doesn't change this behaviour either. 

Am I doing something wrong or is this a bug? 
Thanks.

**Comment by millermedeiros** [comment] 2013-04-29 15:54
duplicate of #8

**Closed as completed by millermedeiros** 2013-04-29 15:54 UTC
